

---
title: "independent"
output: html_document
date: '2022-10-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
library(tidyverse)
library(dplyr)
library(stringr)
library(GOfuncR)
```

Get GO children
```{r}
GO_272<-get_child_nodes(c('GO:0000272'))
```

Load MW and Fugassem data, and filter
```{r}
# load FUG
HMP2_fugassem_GO_func_assignment_tsv <- read_delim("HMP2_fugassem_GO.func_assignment.tsv.gz", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

# make pattern matching much easier. This is a terrible thing to do if GO IDs are not all 10 digits long but otherwise makes code much simpler
HMP2_fugassem_GO_func_assignment_tsv$GO<-substr(HMP2_fugassem_GO_func_assignment_tsv$func, 1, 10)

# raw file: 1,263,290 rows
length(rownames(HMP2_fugassem_GO_func_assignment_tsv))

# filter FUG
HMP2_fugassem_GO_func_assignment_tsv <-HMP2_fugassem_GO_func_assignment_tsv %>% filter(score > 0.9) %>% filter(GO %in% GO_272$child_go_id) %>% filter(str_detect(taxa_lineage, "p__Bacteroidetes|p__Proteobacteria"))

#173 candidates
length(rownames(HMP2_fugassem_GO_func_assignment_tsv))

# load MW
only_bacteroidetes <- read.csv("only_bacteroidetes.csv")
only_proteobacteria <- read.csv("only_proteobacteria.csv")
##load MetaWIBELE files

# No good reason not to combine these and then do filtering
MW<-rbind(only_bacteroidetes, only_proteobacteria)
MW <- MW %>% filter(Priority.score > 0.9)

# There are 26,643 rows from Bact/Prot in MW data w/ priority > 0.9
length(rownames(MW))

# three candidates depleted in dysbiotic IBD. 
mw_cand<- MW %>% filter(GO.BP. %in% GO_272$child_go_id | GO.CC. %in% GO_272$child_go_id | GO.MF. %in% GO_272$child_go_id)


# double check - is GO.BP the only matching column? Yes.
double_check<- MW %>% filter(GO.BP. %in% GO_272$child_go_id)

bothMW_FG_inner_join<-(inner_join(mw_cand,HMP2_fugassem_GO_func_assignment_tsv,by=c("familyID"="feature")))

```

```{r protein_families_common_in_FUG_and_MW}
## 173 candidates from FUG that > 0.9 + taxonomy + correct GO category
## 26643 candidates from MW with same taxonomy + priority > 0.9
## FUG "feature" and MW "familyID" -> intersect

common_families <- intersect(MW$familyID, HMP2_fugassem_GO_func_assignment_tsv$feature)
newly_annotated <- HMP2_fugassem_GO_func_assignment_tsv[which(HMP2_fugassem_GO_func_assignment_tsv$feature %in% common_families & HMP2_fugassem_GO_func_assignment_tsv$new_ann == 1),]
all_families <- HMP2_fugassem_GO_func_assignment_tsv[which(HMP2_fugassem_GO_func_assignment_tsv$feature %in% common_families),]
rownames(MW) <- MW$familyID
all_families <- as.data.frame(all_families)
rownames(all_families) <- all_families$feature
all_fams_in_MW <- MW[rownames(all_families),]
all_families_all_info <- cbind(all_families, all_fams_in_MW)
```

```{r}
write.csv(all_families_all_info, "all_families_all_info.csv")
write.csv(newly_annotated, "newly_annotated.csv")
```
